### ISSUE TITLE
Create utility function that given a URL for a schema network...

### ISSUE THREAD

**Issue by agbeltran** [FAIRsharing/jsonldschema#44]
... creates the required input for the ```FullSemDiff```class in the form:
- "name":  < name of the schema network >
-  "schemas": <dictionary of pairs (schema name, schema content)>
- "contexts": <dictionary of pairs (schema name, context file content)>

e.g. https://github.com/FAIRsharing/jsonldschema/blob/INSTANCE-VALIDATION/tests/data/dats.json

**Comment by terazus** [comment]
How do i know where to get the autmatocially get the contexts URL? 
If would work for DATS/MIACA/MIACME, as I know the naming convention the recompose the URL. What about other schemas?
I can create the input for FullSemDiff but I need the contexts URLs

**Comment by agbeltran** [comment]
The input file as described in the issue should provide the mapping
information. It should be the same mapping file as being used for the
documenter when displaying the semantic values.

**Comment by terazus** [comment]
closing
