### ISSUE TITLE
Change metadata of merged schema

### ISSUE THREAD

**Issue by agbeltran** [FAIRsharing/jsonldschema#96]
In the merge functionality, the merged schema gets the metadata of the primary schema. Provide some metadata reflecting the merge in the root schema

**Comment by agbeltran** [comment]
e.g. in https://fairsharing.github.io/JSONschema-documenter/?schema_url=https://w3id.org/mircat/miaca_miacme_merge/schema/miaca_miacme_merged_schema.json

the main schema still has title/description about MIACA (e.g. "MIACA (Minimum Information about a Cellular Assay) schema ")

**Comment by agbeltran** [comment]
This actually seems not to have been sorted in #98 and I merged prematurely?

**Comment by agbeltran** [comment]
In the case of merging two networks where the root schemas are exactly equivalent, in a schema that is not the root we wouldn't change the description, but in the root schemas we want to change the description to reflect that this is a new network (resulting from the merge of the other two).

**Comment by terazus** [comment]
Change the ['properties']["@type"] of merged elements
